// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhfrglszhbtmnpcxqkyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoZnJnbHN6aGJ0bW5wY3hxa3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTU2MDEsImV4cCI6MjA3MzkzMTYwMX0.AdBoBRbhOqXCVD2cQTaoho86H210fId3nn_rqiRUWdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});